sudo: false
dist: xenial
language: python
python:
  - "2.7"
  - "3.7"
  - "pypy"
install: pip install -U pip tox codecov
script: tox -e coverage
after_success: codecov
matrix:
  allow_failures:
    - python: "pypy"
